In [149]:
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
from selenium.webdriver.edge.service import Service
import time
import pandas as pd

In [5]:
url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1'
r=requests.get(url)
print(r)

<Response [200]>

In [9]:
url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1'
path='msedgedriver.exe'
s=Service(path)
driver=webdriver.Edge(service=s)
driver.get(url)
time.sleep(5)
data=driver.page_source
driver.quit()

In [13]:
soup=BeautifulSoup(data,'lxml')
print(soup.prettify())

<html lang="en">
 <head>
  <script async="async" src="https://flipkart.d1.sc.omtrdc.net/id?d_visid_ver=1.5.4&amp;callback=s_c_il%5B0%5D._setAnalyticsFields&amp;mcorgid=17EB401053DAF4840A490D4C%40AdobeOrg&amp;mid=36486774342545977623131359547925804624" type="text/javascript">
  </script>
  <style id="react-native-stylesheet">
  </style>
  <script async="async" src="https://dpm.demdex.net/id?d_visid_ver=1.5.4&amp;d_rtbd=json&amp;d_ver=2&amp;d_orgid=17EB401053DAF4840A490D4C%40AdobeOrg&amp;d_nsid=0&amp;d_cb=s_c_il%5B0%5D._setMarketingCloudFields" type="text/javascript">
  </script>
  <link href="https://rukminim2.flixcart.com" rel="preconnect"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/atlas.chunk.8dd48d.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.e4e719.css" rel="stylesheet"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="102988293558" property="fb:page_id"/>
  <meta content="658873552,624500995,100000233612389" property="fb:admins"/>
  <link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/>
  <link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/>
  <meta content="website" property="og:type"/>
  <meta content="Flipkart.com" name="og_site_name" property="og:site_name"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/>
  <meta content="app" name="twitter:card"/>
  <meta content="@flipkart" name="twitter:site"/>
  <meta content="@flipkart" name="twitter:creator"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/>
  <meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/>
  <meta content="in" name="twitter:app:country"/>
  <meta content="Flipkart" name="al:ios:app_name"/>
  <meta content="742044692" name="al:ios:app_store_id"/>
  <meta content="Flipkart" name="twitter:app:name:iphone"/>
  <meta content="742044692" name="twitter:app:id:iphone"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/>
  <meta content="Flipkart" name="twitter:app:name:ipad"/>
  <meta content="742044692" name="twitter:app:id:ipad"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/>
  <meta content="Flipkart" name="twitter:app:name:googleplay"/>
  <meta content="com.flipkart.android" name="twitter:app:id:googleplay"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/>
  <style>
   #container {
			height: 100%;
		}
  </style>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.3ae18725.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/atlas.chunk.43936284.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.chunk.b5797b2b.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.chunk.fc48b174.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.chunk.5bf22e07.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.chunk.ba0b3035.js">
  </script>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css" rel="stylesheet"/>
  <title>
   Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com
  </title>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"/>
  <meta content="Laptops Under 50000" name="Keywords"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"/>
  <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"/>
  <!--[if IE 9 ]>
	<script nonce="13192939904111101575">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]-->
  <!--[if !IE]><!-->
  <script nonce="">
   if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}
  </script>
  <!--<![endif]-->
  <script nonce="">
   ;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [31]:
nxt_pg=soup.find('a',class_='_9QVEpD')
cp_nxt_pg='https://www.flipkart.com'+nxt_pg['href']
cp_nxt_pg

'https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2'

# Using loop to automate

In [39]:
url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1'
path='msedgedriver.exe'
s=Service(path)
driver=webdriver.Edge(service=s)
driver.get(url)
time.sleep(5)
data=driver.page_source
# driver.quit()
soup=BeautifulSoup(data,'lxml')

i=0
while i<=10:
    nxt_pg=soup.find('a',class_='_9QVEpD')
    cp_nxt_pg='https://www.flipkart.com'+nxt_pg['href']
    print(cp_nxt_pg)
    
    url=cp_nxt_pg
    driver.get(url)
    # time.sleep(0)
    data=driver.page_source
    
    soup=BeautifulSoup(data,'lxml')
    i+=1

driver.quit()

https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2

# Get Specific Links for continuous page

In [60]:
path='msedgedriver.exe'
s=Service(path)
driver=webdriver.Edge(service=s)

for i in range(2 ,10):

    url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page='+str(i)
    
    driver.get(url)
    time.sleep(1)
    page=driver.page_source
    soup=BeautifulSoup(page,'lxml')
    nxt_pg=soup.find('a',class_='_9QVEpD')['href']
    cmp_nxt_pg="https://www.flipkart.com"+nxt_pg
    print(cmp_nxt_pg)
    
driver.quit()

https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=4
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=5
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=6
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=7
https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=8

# Extracting Data

In [70]:
url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page='+str(1)
path='msedgedriver.exe'
s=Service(path)
driver=webdriver.Edge(service=s)
driver.get(url)
time.sleep(1)
page=driver.page_source
driver.quit()

In [72]:
soup=BeautifulSoup(page,'lxml')
print(soup.prettify())

<html lang="en">
 <head>
  <script async="async" src="https://flipkart.d1.sc.omtrdc.net/id?d_visid_ver=1.5.4&amp;callback=s_c_il%5B0%5D._setAnalyticsFields&amp;mcorgid=17EB401053DAF4840A490D4C%40AdobeOrg&amp;mid=91561925526492200845928624879902645285" type="text/javascript">
  </script>
  <script async="async" src="https://dpm.demdex.net/id?d_visid_ver=1.5.4&amp;d_rtbd=json&amp;d_ver=2&amp;d_orgid=17EB401053DAF4840A490D4C%40AdobeOrg&amp;d_nsid=0&amp;d_cb=s_c_il%5B0%5D._setMarketingCloudFields" type="text/javascript">
  </script>
  <style id="react-native-stylesheet">
  </style>
  <link href="https://rukminim2.flixcart.com" rel="preconnect"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/atlas.chunk.8dd48d.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.e4e719.css" rel="stylesheet"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="102988293558" property="fb:page_id"/>
  <meta content="658873552,624500995,100000233612389" property="fb:admins"/>
  <link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/>
  <link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/>
  <meta content="website" property="og:type"/>
  <meta content="Flipkart.com" name="og_site_name" property="og:site_name"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/>
  <meta content="app" name="twitter:card"/>
  <meta content="@flipkart" name="twitter:site"/>
  <meta content="@flipkart" name="twitter:creator"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/>
  <meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/>
  <meta content="in" name="twitter:app:country"/>
  <meta content="Flipkart" name="al:ios:app_name"/>
  <meta content="742044692" name="al:ios:app_store_id"/>
  <meta content="Flipkart" name="twitter:app:name:iphone"/>
  <meta content="742044692" name="twitter:app:id:iphone"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/>
  <meta content="Flipkart" name="twitter:app:name:ipad"/>
  <meta content="742044692" name="twitter:app:id:ipad"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/>
  <meta content="Flipkart" name="twitter:app:name:googleplay"/>
  <meta content="com.flipkart.android" name="twitter:app:id:googleplay"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/>
  <style>
   #container {
			height: 100%;
		}
  </style>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.3ae18725.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/atlas.chunk.43936284.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.chunk.b5797b2b.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.chunk.fc48b174.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.chunk.5bf22e07.js">
  </script>
  <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.chunk.ba0b3035.js">
  </script>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css" rel="stylesheet"/>
  <title>
   Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com
  </title>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"/>
  <meta content="Laptops Under 50000" name="Keywords"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"/>
  <meta content="Laptops Under 50000- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"/>
  <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"/>
  <!--[if IE 9 ]>
	<script nonce="16535002069055723759">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]-->
  <!--[if !IE]><!-->
  <script nonce="">
   if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}
  </script>
  <!--<![endif]-->
  <script nonce="">
   ;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [137]:
Laptop_names=[]
Laptop_price=[]
Laptop_rating=[]

names=soup.find_all('div',class_='tUxRFH')
# print(names)
for name in names:
    lap_names=name.find('div',class_='KzDlHZ')
    lap_names_txt=lap_names.text
    Laptop_names.append(lap_names_txt)
    
    price=name.find('div',class_='Nx9bqj _4b5DiR')
    price_txt=price.text
    Laptop_price.append(price_txt)
    
    rating=name.find('div',class_='XQDdHH')
    rating_txt=rating.text if rating else "N/A"
    Laptop_rating.append(rating_txt)
                     
    print(lap_names_txt,price_txt,rating_txt)

MSI Modern 14 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) Modern 14 C12MO-1249IN ... ₹36,990 N/A
Acer Aspire 3 Intel Core i3 13th Gen 1305U - (8 GB/512 GB SSD/Windows 11 Home) A324-53 Thin and Light ... ₹30,990 4.2
ASUS Vivobook 15 Intel Core i3 12th Gen 1215U - (16 GB/512 GB SSD/Windows 11 Home) X1504ZA-NJ342WS Thi... ₹35,470 4.3
ASUS Vivobook 15, with Backlit Keyboard, Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 H... ₹48,990 4.2
ASUS Vivobook 15, with Backlit Keyboard, Intel Core i5 13th Gen 1335U - (8 GB/512 GB SSD/Windows 11 Ho... ₹45,990 4.2
Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U - (8 GB/512 GB SSD/Windows 11 Home) A325-42 Thin and Light L... ₹25,990 4.2
Acer Aspire 3 Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Windows 11 Home) A324-53 Thin and Light... ₹42,990 4.3
Acer Aspire 3 Backlit Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 Home) A324-51 Thin a... ₹40,980 4.1
ASUS Vivobook 15 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) X1504VA-NJ323WS Thin... ₹36,990 4.3
ASUS Vivobook 15 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) X1504ZA-NJ527WS|X150... ₹42,990 4.2
Lenovo Chromebook MediaTek Kompanio 520 - (8 GB/128 GB EMMC Storage/Chrome OS) 14M868 Thin and Light L... ₹16,990 3.8
HP Chromebook Intel Celeron Dual Core N4120 - (4 GB/64 GB EMMC Storage/Chrome OS) 14a-ca0506TU Chromeb... ₹19,990 3.9
SAMSUNG Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-L... ₹39,990 4.5
Acer Aspire 3 Intel Core i7 12th Gen 1255U - (16 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light... ₹43,990 4.3
Acer Aspire Lite with Backlit Keyboard, Intel Core i7 12th Gen 1255U - (16 GB/512 GB SSD/Windows 11 Ho... ₹44,900 4.4
HP 15s Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 Home) 15s-fq5112TU Thin and Light L... ₹49,400 4.1
Lenovo Chromebook Intel Pentium Quad Core N100 - (4 GB/128 GB EMMC Storage/Chrome OS) 14IAN8 Chromeboo... ₹19,990 3.6
Thomson NEO Core Series Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 Home) IN-N15I Thin... ₹32,990 4
ASUS Vivobook 15 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) X1504ZA-NJ521WS|X150... ₹42,990 4.2
ASUS Vivobook 15 Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) X1504VA-NJ320WS Thin... ₹36,990 3.8
Thomson NEO Core Series Intel Core i7 12th Gen 1255U - (16 GB/512 GB SSD/Windows 11 Home) IN-N15I Thin... ₹37,990 3.2
Thomson NEO Core Series Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) IN-N15I Thin ... ₹21,990 3.8
Acer Aspire Lite AMD Ryzen 5 Hexa Core 5625U - (16 GB/1 TB SSD/Windows 11 Home) AL15-41 Thin and Light... ₹41,730 4
ASUS Vivobook 15 Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 Home) X1504ZA-NJ549WS Thi... ₹48,990 4.2

In [139]:
import pandas as pd

In [141]:
data=pd.DataFrame({
    'Laptop_names':Laptop_names,
    'Laptop_price':Laptop_price,
    'Laptop_rating':Laptop_rating
})

In [143]:
data

,Laptop_names,Laptop_price,Laptop_rating
0,MSI Modern 14 Intel Core i5 12th Gen 1235U - (...,"₹36,990",N/A
1,Acer Aspire 3 Intel Core i3 13th Gen 1305U - (...,"₹30,990",4.2
2,ASUS Vivobook 15 Intel Core i3 12th Gen 1215U ...,"₹35,470",4.3
3,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹48,990",4.2
4,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹45,990",4.2
5,Acer Aspire 3 AMD Ryzen 3 Quad Core 7330U - (8...,"₹25,990",4.2
6,Acer Aspire 3 Intel Core i5 13th Gen 1334U - (...,"₹42,990",4.3
7,Acer Aspire 3 Backlit Intel Core i5 12th Gen 1...,"₹40,980",4.1
8,ASUS Vivobook 15 Intel Core i3 13th Gen 1315U ...,"₹36,990",4.3
9,ASUS Vivobook 15 Intel Core i5 12th Gen 1235U ...,"₹42,990",4.2
10,Lenovo Chromebook MediaTek Kompanio 520 - (8 G...,"₹16,990",3.8
11,HP Chromebook Intel Celeron Dual Core N4120 - ...,"₹19,990",3.9
12,SAMSUNG Galaxy Book4 Metal Intel Core i3 13th ...,"₹39,990",4.5
13,Acer Aspire 3 Intel Core i7 12th Gen 1255U - (...,"₹43,990",4.3
14,"Acer Aspire Lite with Backlit Keyboard, Intel ...","₹44,900",4.4
15,HP 15s Intel Core i5 12th Gen 1235U - (16 GB/5...,"₹49,400",4.1
16,Lenovo Chromebook Intel Pentium Quad Core N100...,"₹19,990",3.6
17,Thomson NEO Core Series Intel Core i5 12th Gen...,"₹32,990",4
18,ASUS Vivobook 15 Intel Core i5 12th Gen 1235U ...,"₹42,990",4.2
19,ASUS Vivobook 15 Intel Core i3 13th Gen 1315U ...,"₹36,990",3.8
20,Thomson NEO Core Series Intel Core i7 12th Gen...,"₹37,990",3.2
21,Thomson NEO Core Series Intel Core i3 12th Gen...,"₹21,990",3.8
22,Acer Aspire Lite AMD Ryzen 5 Hexa Core 5625U -...,"₹41,730",4
23,ASUS Vivobook 15 Intel Core i5 12th Gen 1235U ...,"₹48,990",4.2

# Final Project - Automating to get upto 5 pages data and save to CSV File

In [152]:
Laptop_names=[]
Laptop_price=[]
Laptop_rating=[]

path='msedgedriver.exe'
s=Service(path)
driver=webdriver.Edge(service=s)

for i in range(1,6):
    url='https://www.flipkart.com/search?q=laptops+under+50000&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page='+str(i)
    
    driver.get(url)
    time.sleep(1)
    page=driver.page_source
    soup=BeautifulSoup(page,'lxml')

    
    names=soup.find_all('div',class_='tUxRFH')
    # print(names)
    for name in names:
        lap_names=name.find('div',class_='KzDlHZ')
        lap_names_txt=lap_names.text
        Laptop_names.append(lap_names_txt)
        
        price=name.find('div',class_='Nx9bqj _4b5DiR')
        price_txt=price.text
        Laptop_price.append(price_txt)
        
        rating=name.find('div',class_='XQDdHH')
        rating_txt=rating.text if rating else "N/A"
        Laptop_rating.append(rating_txt)
                         

driver.quit()

data=pd.DataFrame({
    'Laptop_names':Laptop_names,
    'Laptop_price':Laptop_price,
    'Laptop_rating':Laptop_rating
})
print(data)

                                          Laptop_names Laptop_price  \
0    Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...      ₹19,990
1    Acer Aspire 3 Intel Core i3 13th Gen 1305U - (...      ₹30,990
2    ASUS Vivobook 15 Intel Core i3 12th Gen 1215U ...      ₹35,470
3    ASUS Vivobook 15, with Backlit Keyboard, Intel...      ₹48,990
4    ASUS Vivobook 15, with Backlit Keyboard, Intel...      ₹45,990
..                                                 ...          ...
115  Lenovo IdeaPad 3 Intel Intel Core i5 12th Gen ...      ₹48,999
116  HP 15s AMD Ryzen 5 Quad Core 7520U - (8 GB/512...      ₹50,990
117  Lenovo IdeaPad 1 AMD Ryzen 7 Octa Core 5700U -...      ₹45,990
118  Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...      ₹47,990
119  ASUS Vivobook 15 OLED Intel Core i3 12th Gen 1...      ₹46,070

    Laptop_rating
0             3.7
1             4.2
2             4.3
3             4.2
4             4.2
..            ...
115           3.7
116           4.2
117           4.2
118           4.4
119           4.4

[120 rows x 3 columns]

In [156]:
data.to_csv("Flipkart_webScraping.csv")

In [160]:
pd.read_csv("Flipkart_webScraping.csv")

,Unnamed: 0,Laptop_names,Laptop_price,Laptop_rating
0,0,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹19,990",3.7
1,1,Acer Aspire 3 Intel Core i3 13th Gen 1305U - (...,"₹30,990",4.2
2,2,ASUS Vivobook 15 Intel Core i3 12th Gen 1215U ...,"₹35,470",4.3
3,3,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹48,990",4.2
4,4,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹45,990",4.2
...,...,...,...,...
115,115,Lenovo IdeaPad 3 Intel Intel Core i5 12th Gen ...,"₹48,999",3.7
116,116,HP 15s AMD Ryzen 5 Quad Core 7520U - (8 GB/512...,"₹50,990",4.2
117,117,Lenovo IdeaPad 1 AMD Ryzen 7 Octa Core 5700U -...,"₹45,990",4.2
118,118,Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...,"₹47,990",4.4
119,119,ASUS Vivobook 15 OLED Intel Core i3 12th Gen 1...,"₹46,070",4.4

In [162]:
data

,Laptop_names,Laptop_price,Laptop_rating
0,Acer Aspire 3 Intel Celeron Dual Core - (8 GB/...,"₹19,990",3.7
1,Acer Aspire 3 Intel Core i3 13th Gen 1305U - (...,"₹30,990",4.2
2,ASUS Vivobook 15 Intel Core i3 12th Gen 1215U ...,"₹35,470",4.3
3,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹48,990",4.2
4,"ASUS Vivobook 15, with Backlit Keyboard, Intel...","₹45,990",4.2
...,...,...,...
115,Lenovo IdeaPad 3 Intel Intel Core i5 12th Gen ...,"₹48,999",3.7
116,HP 15s AMD Ryzen 5 Quad Core 7520U - (8 GB/512...,"₹50,990",4.2
117,Lenovo IdeaPad 1 AMD Ryzen 7 Octa Core 5700U -...,"₹45,990",4.2
118,Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...,"₹47,990",4.4
119,ASUS Vivobook 15 OLED Intel Core i3 12th Gen 1...,"₹46,070",4.4